source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '7.1'

pod 'Parse'
pod 'AKNumericFormatter'
pod 'AFNetworking', '~> 2.2'
pod 'BlocksKit', '~> 2.2.2'
pod 'GoogleAnalytics'
pod 'MBProgressHUD', '~> 0.8'
pod 'SDWebImage', '~> 3.6'
pod 'UICKeyChainStore', '~> 1.0.5'
#pod 'Facebook-iOS-SDK', '~> 4.1'
pod 'FBSDKCoreKit'
pod 'FBSDKShareKit'
pod 'GoogleMaps'
pod 'Reachability'
pod 'FLKAutoLayout', '~> 0.2.1'
pod 'PayPal-iOS-SDK'
pod 'Fabric'
pod 'Crashlytics'
pod 'Branch'
pod 'FBSDKShareKit'
pod 'VK-ios-sdk'
